audit_header: false
title: San Diego Real Estate Video Blog with Joe Corbisiero
description: Our mission at Dream Homes Team is to be your best resource for San Diego real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Dream Homes Team, your professional San Diego Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Joe Corbisiero
  title:
  license_number: 'CA DRE#: 01886351'
  about_markdown: |
    A great team leader, hard worker, knowledgeable, honest, a true listener and open to learning. I build dreams. As a San Diego Real Estate Professional, I meet with outstanding people every day, whether you're a first time home buyer, an investor, a family looking to grow into a new home, or you are ready to sell your home. Allow me the opportunity to earn your trust and your friendship.

    I might be old fashioned, but I believe we still live in a world where ethical and moral integrity is important and should be part of our everyday lives. I work hard for my clients, I am on call 24/7, 365 days a year for my clients. I have been in the Real Estate Business since 2006, I operate in Europe and California, but I have access to some deals all over the country. My network is huge and I can guarantee you, above all else service and dependability. I am Joe Corbisiero and I want to be your Realtor!
  brand: Dream Homes Team
  brokerage: Compass
  market: San Diego
  address: 2165 San Diego Ave Suite 201 San Diego, CA 92110
  phone: 760-201-9252
  phone_type:
  phone2:
  phone2_type:
  email:
  url: https://www.bestsandiegohomesforsale.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.bestsandiegohomesforsale.com/homevalue/default
  second_CTA_text: Home Search
  second_CTA_URL: https://www.bestsandiegohomesforsale.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your San Diego Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.bestsandiegohomesforsale.com/homevalue/default

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a San Diego Home?"
    CTA_text2: "Search the entire MLS for your San Diego home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.bestsandiegohomesforsale.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/JoeCorbisieroSanDiegoRealtor
  linkedin_url: https://www.linkedin.com/in/joesellssandiego
  youtube_url: http://www.youtube.com/c/JoeCorbisieroSellsSanDiego
  twitter_url: https://twitter.com/DreamHomesTeam
  instagram_url: https://www.instagram.com/dream_homes_team_sd
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'San Diego Real Estate Podcast with Joe Corbisiero'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Dream Homes Team - your professional San Diego Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Diego, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Joe Corbisiero'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  # hero_text: San Diego Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#8BCDF4'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
